#!/usr/bin/env python3
"""Generate the signed-image fixtures the host tests verify.

Run at configure time by test/CMakeLists.txt. Produces, into the build tree:

    signing_key.c    a definition of rw_ota_public_key for a throwaway key
    ota_fixture.h    the signed image built with that key, as a C array

The key is generated fresh and thrown away, so the test never needs the real signing key and CI
needs nothing installed but openssl. What this proves is the thing that cannot be proved by
reading either side: that tools/sign_image.py and src/ota/image.c agree on the format, including
the DER-to-raw signature conversion, which is wrong for roughly half of all keys if done by
slicing.

SPDX-License-Identifier: MIT
"""

import argparse
import hashlib
import importlib.util
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
FIRMWARE = HERE.parent.parent


def load_signer():
    spec = importlib.util.spec_from_file_location("sign_image", FIRMWARE / "tools" / "sign_image.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def c_array(name, data):
    rows = "\n".join(
        "    " + " ".join(f"0x{b:02x}," for b in data[i : i + 12]) for i in range(0, len(data), 12)
    )
    return f"static const unsigned char {name}[] = {{\n{rows}\n}};\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir", type=pathlib.Path)
    args = ap.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    signer = load_signer()
    key = args.outdir / "test-signing-key.pem"
    if not key.exists():
        subprocess.run(
            ["openssl", "ecparam", "-name", "prime256v1", "-genkey", "-noout", "-out", str(key)],
            check=True, capture_output=True,
        )

    # Emit the public half as the rw_ota_public_key the test binary links against.
    emit = subprocess.run(
        [sys.executable, str(FIRMWARE / "tools" / "emit_signing_key.py"), str(key),
         "--name", "throwaway, generated for the host tests"],
        check=True, capture_output=True, text=True,
    ).stdout
    (args.outdir / "signing_key.c").write_text(emit, encoding="utf-8")

    # A payload with no structure of its own; the format does not care what it carries.
    payload = bytes((i * 7 + 11) & 0xFF for i in range(4096))
    header = signer.build_header(payload, "9.9.9", "PW")
    signature = signer.sign(hashlib.sha256(header[:64]).digest(), key)
    image = header[:64] + signature + payload

    # A second image for the other board, so the board check is exercised against a signature
    # that is otherwise perfectly valid.
    other_header = signer.build_header(payload, "9.9.9", "P2W")
    other = other_header[:64] + signer.sign(hashlib.sha256(other_header[:64]).digest(), key) + payload

    (args.outdir / "ota_fixture.h").write_text(
        "/* Generated by test/tools/make_fixture.py. Do not edit. */\n"
        "#ifndef RW_OTA_FIXTURE_H\n#define RW_OTA_FIXTURE_H\n\n"
        f"#define RW_FIXTURE_PAYLOAD_LEN {len(payload)}\n"
        '#define RW_FIXTURE_VERSION "9.9.9"\n\n'
        + c_array("k_ota_image", image)
        + "\n"
        + c_array("k_ota_image_other_board", other)
        + "\n#endif\n",
        encoding="utf-8",
    )
    print(f"fixtures written to {args.outdir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
